Support for development on Mac OS X.

diff --git a/scripts/postgresql-init b/scripts/postgresql-init
--- a/scripts/postgresql-init
+++ b/scripts/postgresql-init
@@ -6,22 +6,34 @@ PSQL_HOST="localhost"
 CONTRIB_DIR=""
 POSTGIS_DIR=""
 if [ -d /usr/share/postgresql/8.4 ]; then
-  CONTRIB_DIR="/usr/share/postgresql/8.4/contrib"
-  POSTGIS_DIR="/usr/share/postgresql/8.4/contrib/postgis-1.5"
-elif [ -d /usr/share/postgresql/9.1 ]; then
-  CONTRIB_DIR="/usr/share/postgresql/9.1/contrib"
-  POSTGIS_DIR="/usr/share/postgresql/9.1/contrib/postgis-1.5"
-elif [ -d /usr/share/postgresql-8.3 ]; then
-  CONTRIB_DIR="/usr/share/postgresql-8.3/contrib"
-  POSTGIS_DIR="/usr/share/postgresql-8.3/contrib/postgis-1.5"
-elif [ -d /usr/local/share/postgresql ]; then
-  CONTRIB_DIR="/usr/local/share/postgresql/contrib"
-  POSTGIS_DIR="/usr/local/share/postgis"
-  PSQL_USER_ARG=""
-else
-  echo "!!! PostgreSQL contrib directory not found. Please edit"
-  echo "!!! the database initialization script!"
-  exit 1
+    CONTRIB_DIR="/usr/share/postgresql/8.4/contrib"
+    POSTGIS_DIR="/usr/share/postgresql/8.4/contrib/postgis-1.5"
+fi
+if [ -d /usr/share/postgresql/9.1 ]; then
+    CONTRIB_DIR="/usr/share/postgresql/9.1/contrib"
+    POSTGIS_DIR="/usr/share/postgresql/9.1/contrib/postgis-1.5"
+fi
+if [ -d /usr/share/postgresql-8.3 ]; then
+    CONTRIB_DIR="/usr/share/postgresql-8.3/contrib"
+    POSTGIS_DIR="/usr/share/postgresql-8.3/contrib/postgis-1.5"
+fi
+if [ -d /usr/local/share/postgresql ]; then
+    CONTRIB_DIR="/usr/local/share/postgresql/contrib"
+    POSTGIS_DIR="/usr/local/share/postgis"
+    PSQL_USER_ARG=""
+fi
+if [ -d /usr/local/Cellar/postgresql9/9.0.11 ]; then
+    CONTRIB_IDR="/usr/local/Cellar/postgresql9/9.0.11/share/postgresql9/contrib"
+    PSQL_USER_ARG=""
+fi
+if [ -d /usr/local/Cellar/postgis15/1.5.8 ]; then
+    POSTGIS_DIR="/usr/local/Cellar/postgis15/1.5.8/share/postgis"
+fi
+
+if  [[ -ne "$CONTRIB_DIR" && -ne "$POSTGIS_DIR" ]]; then
+    echo "!!! PostgreSQL or PostGIS contrib directories not found."
+    echo "!!! Please edit the database initialization script!"
+    exit 1
 fi
 
 # Drop can fail if there is no database already defined
